version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_workspace: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: network_ui_local_django
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8002:8000"
    command: /start

  worker:
    build:
      context: .
      dockerfile: ./compose/local/worker/Dockerfile
    image: network_ui_local_worker
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
      - local_workspace:/tmp/workspace
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: network_ui_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:3.0
