version: '3'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: network_ui_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /daphne.sh

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: network_ui_production_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file:
      - ./.envs/.production/.postgres

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: network_ui_production_nginx
    volumes:
        - ./compose/production/nginx/conf.d:/etc/nginx/conf.d
        - ./network_ui/static:/static/static
    depends_on:
      - django
    ports:
      - "0.0.0.0:8002:80"

  redis:
    image: redis:3.2
