# Generated by Django 2.0.8 on 2018-11-12 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('host_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('key_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=2000)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('playbook_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=2000)),
                ('contents', models.TextField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insights_integration.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='PlaybookRun',
            fields=[
                ('playbook_run_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('create_time', models.DateTimeField()),
                ('host_pattern', models.CharField(blank=True, max_length=2000)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insights_integration.Inventory')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insights_integration.Key')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insights_integration.Playbook')),
            ],
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('task_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=2000)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insights_integration.Host')),
            ],
        ),
        migrations.CreateModel(
            name='TaskResultPlaybookRun',
            fields=[
                ('task_result_playbook_run_id', models.AutoField(primary_key=True, serialize=False)),
                ('playbook_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insights_integration.PlaybookRun')),
                ('task_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insights_integration.TaskResult')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerQueue',
            fields=[
                ('worker_queue_id', models.AutoField(primary_key=True, serialize=False)),
                ('playbook_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insights_integration.PlaybookRun')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insights_integration.Worker')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insights_integration.Inventory'),
        ),
    ]
