# Generated by Django 2.0.8 on 2018-11-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights_integration', '0002_auto_20181113_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host_vars',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
