# Generated by Django 2.0.8 on 2018-11-14 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insights_integration', '0003_host_host_vars'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybookRunLog',
            fields=[
                ('playbook_run_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('value', models.TextField()),
                ('playbook_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insights_integration.PlaybookRun')),
            ],
        ),
    ]
