# Generated by Django 2.0.8 on 2018-10-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_ui_dev', '0002_auto_20180824_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='topology',
            name='uuid',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
