# Generated by Django 2.0.8 on 2018-10-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_ui_dev', '0004_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('replay_id', models.AutoField(primary_key=True, serialize=False)),
                ('replay_data', models.TextField()),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
